theme: jekyll-theme-modernist
title: MyUH Club Home Page
description: This is the homepage for the MyUH Club Project. Our goal is to create a platform of communication between students at the University of Hawaii at Manoa, as well as its Registered Independent Organizations.
